# -*- coding: utf-8 -*-
"""Otimização2023.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keAwzDzLuCCact5cTxRsLWl8Klu8DDDB
"""

!pip install pulp

from pulp import *

problema1 = LpProblem('otimizadofrete',LpMinimize)

x11 = LpVariable('x11', lowBound=0)
x12 = LpVariable('x12', lowBound=0)
x13 = LpVariable('x13', lowBound=0)
x14 = LpVariable('x14', lowBound=0)
x15 = LpVariable('x15', lowBound=0)
x16 = LpVariable('x16', lowBound=0)
x17 = LpVariable('x17', lowBound=0)
x18 = LpVariable('x18', lowBound=0)
x19 = LpVariable('x19', lowBound=0)
x110 = LpVariable('x110', lowBound=0)
x111 = LpVariable('x111', lowBound=0)
x112 = LpVariable('x112', lowBound=0)
x113 = LpVariable('x113', lowBound=0)
x114 = LpVariable('x114', lowBound=0)
x115 = LpVariable('x115', lowBound=0)
x116 = LpVariable('x116', lowBound=0)
x117 = LpVariable('x117', lowBound=0)
x118 = LpVariable('x118', lowBound=0)
x119 = LpVariable('x119', lowBound=0)
x120 = LpVariable('x120', lowBound=0)
x121 = LpVariable('x121', lowBound=0)
x122 = LpVariable('x122', lowBound=0)
x123 = LpVariable('x123', lowBound=0)
x124 = LpVariable('x124', lowBound=0)
x125 = LpVariable('x125', lowBound=0)
x126 = LpVariable('x126', lowBound=0)
x127 = LpVariable('x127', lowBound=0)
x128 = LpVariable('x128', lowBound=0)
x129 = LpVariable('x129', lowBound=0)
x130 = LpVariable('x130', lowBound=0)
x131 = LpVariable('x131', lowBound=0)
x132 = LpVariable('x132', lowBound=0)
x133 = LpVariable('x133', lowBound=0)
x134 = LpVariable('x134', lowBound=0)
x135 = LpVariable('x135', lowBound=0)
x139 = LpVariable('x139', lowBound=0)
x140 = LpVariable('x140', lowBound=0)
x141 = LpVariable('x141', lowBound=0)
x142 = LpVariable('x142', lowBound=0)
x143 = LpVariable('x143', lowBound=0)
x144 = LpVariable('x144', lowBound=0)
x145 = LpVariable('x145', lowBound=0)
x146 = LpVariable('x146', lowBound=0)
x147 = LpVariable('x147', lowBound=0)
x148 = LpVariable('x148', lowBound=0)
x149 = LpVariable('x149', lowBound=0)
x150 = LpVariable ('x150', lowBound=0)
x151 = LpVariable('x151', lowBound=0)
x21 = LpVariable('x21', lowBound=0)
x22 = LpVariable('x22', lowBound=0)
x23 = LpVariable('x23', lowBound=0)
x24 = LpVariable('x24', lowBound=0)
x25 = LpVariable('×25', lowBound=0)
x26 = LpVariable('x26', lowBound=0)
x27 = LpVariable('x27', lowBound=0)
x28 = LpVariable('x28', lowBound=0)
x29 = LpVariable('×29', lowBound=0)
x210 = LpVariable ('x210', lowBound=0)
x211 = LpVariable('x211', lowBound=0)
x219 = LpVariable('x219', lowBound=0)
x220 = LpVariable('x220', lowBound=0)
x221 = LpVariable('x221', lowBound=0)
x222 = LpVariable('x222', lowBound=0)
x223 = LpVariable('x223', lowBound=0)
x224 = LpVariable('x224', lowBound=0)
x225 = LpVariable('x225', lowBound=0)
x226 = LpVariable('x226', lowBound=0)
x227 = LpVariable('x227', lowBound=0)
x228 = LpVariable('x228', lowBound=0)
x229 = LpVariable('x229', lowBound=0)
x230 = LpVariable('x230', lowBound=0)
x231 = LpVariable('x231', lowBound=0)
x232 = LpVariable('x232', lowBound=0)
x233 = LpVariable('x233', lowBound=0)
x234 = LpVariable('x234', lowBound=0)
x235 = LpVariable('x235', lowBound=0)
x236 = LpVariable('x236', lowBound=0)
x237 = LpVariable('x237', lowBound=0)
x238 = LpVariable('x238', lowBound=0)
x244 = LpVariable('x244', lowBound=0)
x245 = LpVariable('x245', lowBound=0)
x246 = LpVariable('x246', lowBound=0)
x247 = LpVariable('x247', lowBound=0)
x248 = LpVariable('x248', lowBound=0)
x249 = LpVariable('x249', lowBound=0)
x250 = LpVariable('x250', lowBound=0)
x251 = LpVariable('x251', lowBound=0)
x35 = LpVariable('x35', lowBound=0)
x38 = LpVariable('x38', lowBound=0)
x39 = LpVariable('x39', lowBound=0)
x310 = LpVariable('x310', lowBound=0)
x311 = LpVariable('x311', lowBound=0)
x324 = LpVariable('x324', lowBound=0)
x325 = LpVariable('x325', lowBound=0)
x326 = LpVariable('x326', lowBound=0)
x327 = LpVariable('x327', lowBound=0)
x328 = LpVariable('x328', lowBound=0)
x329 = LpVariable('x329', lowBound=0)
x330 = LpVariable('x330', lowBound=0)
x331 = LpVariable('x331', lowBound=0)
x332 = LpVariable('x332', lowBound=0)
x333 = LpVariable('x333', lowBound=0)
x334 = LpVariable('x334', lowBound=0)
x335 = LpVariable('x335', lowBound=0)
x336 = LpVariable('x336', lowBound=0)
x337 = LpVariable('x337', lowBound=0)
x338 = LpVariable('x338', lowBound=0)
x339 = LpVariable('x339', lowBound=0)
x340 = LpVariable('x340', lowBound=0)
x341 = LpVariable('x341', lowBound=0)
x342 = LpVariable('x342', lowBound=0)
x343 = LpVariable('x343', lowBound=0)
x347 = LpVariable('x347', lowBound=0)
x348 = LpVariable('x348', lowBound=0)
x349 = LpVariable('x349', lowBound=0)
x350 = LpVariable('x350', lowBound=0)
x351 = LpVariable('x351', lowBound=0)

problema1 += 0.56*x11 + 0.51*x12 + 0.43*x13 + 0.47*x14 + 0.50*x15 + 0.55*x16 + 0.53*x17 + 0.55*x18 + 0.43*x19 + 0.71*x110 + 0.37*x111 + 0.79*x112 + 0.77*x113 + 0.71*x114 + 0.84*x115 + 0.84*x116 + 0.84*x117 + 0.84*x118 + 0.70*x119 + 0.73*x120 + 0.77*x121 + 0.69*x122 + 0.75*x123 + 0.71*x124 + 0.63*x125 + 0.70*x126 + 0.72*x127 + 0.72*x128 + 0.76*x129 + 0.76*x130 + 0.70*x131 + 0.69*x132 + 0.67*x133 + 0.69*x134 + 0.69*x135 + 0.89*x139 + 0.97*x140 + 0.92*x141 + 0.91*x142 + 0.99*x143 + 0.63*x144 + 0.64*x145 + 0.64*x146 + 0.28*x147 + 0.28*x148 + 0.30*x149 + 0.36*x150 + 0.41*x151 + 0.42*x21 + 0.38*x22 + 0.37*x23 + 0.40*x24 + 0.40*x25 + 0.37*x26 + 0.43*x27 + 0.37*x28 + 0.48*x29 + 0.28*x210 + 0.56*x211 + 0.29*x219 + 0.28*x220 + 0.28*x221 + 0.29*x222 + 0.25*x223 + 0.29*x224 + 0.27*x225 + 0.28*x226 + 0.21*x227 + 0.31*x228 + 0.27*x229 + 0.29*x230 + 0.28*x231 + 0.27*x232 + 0.27*x233 + 0.29*x234 + 0.29*x235 + 0.72*x236 + 0.70*x237 + 0.70*x238 + 0.48*x244 + 0.49*x245 + 0.47*x246 + 0.90*x247 + 0.96*x248 + 1.05*x249 + 1.02*x250 + 1.09*x251 + 0.26*x35 + 0.26*x38 + 0.27*x39 + 0.29*x310 + 0.26*x311 + 0.28*x324 + 0.25*x325 + 0.29*x326 + 0.28*x327 + 0.31*x328 + 0.32*x329 + 0.43*x330 + 0.29*x331 + 0.34*x332 + 0.60*x333 + 0.27*x334 + 0.27*x335 + 0.48*x336 + 0.46*x337 + 0.46*x338 + 0.55*x339 + 0.61*x340 + 0.58*x341 + 0.57*x342 + 0.61*x343 + 0.68*x347 + 0.72*x348 + 0.61*x349 + 0.68*x350 + 0.63*x351

problema1 += x11 + x12 + x13 + x14 + x15 + x16 + x17 + x18 + x19 + x110 + x111 + x112 + x113 + x114 + x115 + x116 + x117 + x118 + x119 + x120 + x121 + x122 + x123 + x124 + x125 + x126 + x127 + x128 + x129 + x130 + x131 + x132 + x133 + x134 + x135 + x139 + x140 + x141 + x142 + x143 + x144 + x145 + x146 + x147 + x148 + x149 + x150 + x151 <= 90000000



problema1 += x21 + x22 + x23 + x24 + x25 + x26 + x27 + x28 + x29 + x210 + x211 + x219 + x220 + x221 + x222 + x223 + x224 + x225 + x226 + x227 + x228 + x229 + x230 + x231 + x232 + x233 + x234 + x235 + x236 + x237 + x238 + x244 + x245 + x246 + x247 + x248 + x249 + x250 + x251 <= 90000000

problema1 += x35 + x38 + x39 + x310 + x311 + x324 + x325 + x326 + x327 + x328 + x329 + x330 + x331 + x332 + x333 + x334 + x335 + x336 + x337 + x338 + x339 + x340 + x341 + x342 + x343 + x347 + x348 + x349 + x350 + x351 <= 56000000

problema1 += x11 + x21 == 2516400

problema1 += x12 + x22 == 2636100

problema1 += x13 + x23 == 2259600

problema1 += x14 + x24 == 1308600

problema1 += x15 + x25 + x35 == 1648500

problema1 += x16 + x26 == 1578000

problema1 += x17 + x27 == 1724700

problema1 += x18 + x28 + x38 == 1587900

problema1 += x19 + x29 + x39 == 948900

problema1 += x110 + x210 + x310 == 853200

problema1 += x111 + x211 + x311 == 1792800

problema1 += x112 == 1337400

problema1 += x113 == 2138400

problema1 += x114 == 2625600

problema1 += x115 == 1210200

problema1 += x116 == 1073400

problema1 += x117 == 1679700

problema1 += x118 == 1690800

problema1 += x119 + x219 == 1230900

problema1 += x120 + x220 == 2534400

problema1 += x121 + x221 == 1793100

problema1 += x122 + x222 == 1260300

problema1 += x123 + x223 == 1649100

problema1 += x124 + x224 + x324 == 3221400

problema1 += x125 + x225 + x325 == 1761600

problema1 += x126 + x226 + x326 == 2566500

problema1 += x127 + x227 + x327 == 3510300

problema1 += x128 + x228 + x328 == 1569900

problema1 += x129 + x229 + x329 == 1759500

problema1 += x130 + x230 + x330 == 1758900

problema1 += x131 + x231 + x331 == 1539000

problema1 += x132 + x232 + x332 == 3534900

problema1 += x133 + x233 + x333 == 1667100

problema1 += x134 + x234 + x334 == 1317000

problema1 += x135 + x235 + x335 == 1615500

problema1 += x236 + x336 == 862200

problema1 += x237 + x337 == 1688700

problema1 += x238 + x338 == 1182600

problema1 += x139 + x339 == 1775700

problema1 += x140 + x340 == 2554500

problema1 += x141 + x341 == 1349400

problema1 += x142 + x342 == 1624200

problema1 += x143 + x343 == 2590800

problema1 += x144 + x244 == 1372800

problema1 += x145 + x245 == 1205700

problema1 += x146 + x246 == 1788300

problema1 += x147 + x247 + x347 == 1690800

problema1 += x148 + x248 + x348 == 1311600

problema1 += x149 + x249 + x349 == 1688100

problema1 += x150 + x250 + x350 == 1435800

problema1 += x151 + x251 + x351 == 1767900

problema1

problema1.solve()

for v in problema1.variables():
  print(v.name,"=",v.varValue)

print ('Resultado de custo minimo ='), value(problema1.objective)